#!/usr/bin/python

import sys
import zmq

ctx = zmq.Context().instance()
data_sock = ctx.socket(zmq.SUB)
data_sock.setsockopt(zmq.SUBSCRIBE, '')
data_sock.connect('ipc:///tmp/timetag-data')

while True:
    d = data_sock.recv()
    sys.stdout.write(d)
    sys.stdout.flush()
