#!/usr/bin/python

import zmq

ctx = zmq.Context().instance()
ctrl_sock = ctx.socket(zmq.REQ)
ctrl_sock.connect('ipc:///tmp/timetag-ctrl')

def command_line():
    import readline
    while True:
        cmd = raw_input('>>> ')
        ctrl_sock.send_string(cmd)
        print ctrl_sock.recv_string()

if len(sys.argv) > 1:
    ctrl_sock.send_string(' '.join(sys.argv[1:]))
    print ctrl_sock.recv_string()
else:
    command_line()
