#!/usr/bin/python

import zmq

ctx = zmq.Context().instance()
ctrl_sock = ctx.socket(zmq.REQ)
ctrl_sock.connect('ipc:///tmp/timetag-ctrl')

while True:
    cmd = raw_input('>>> ')
    ctrl_sock.send_string(cmd)
    print ctrl_sock.recv_string()
