#!/usr/bin/env python

# print "hello world"
import gtk
from timetag.capture_pipeline import CapturePipeline
from timetag.correlation_plot import CorrelationPlot

print "timetag_correlate - start"
gtk.gdk.threads_init()
pipeline = CapturePipeline()
hp = CorrelationPlot(pipeline)
gtk.main()